before_script:
  # Setup credentials for pipeline
  - git clone -b v4 --single-branch git@git.sami.int.thomsonreuters.com:elf/gitlab-ci-tasks.git ci-tasks
  - node ci-tasks/before_script

stages:
  - test
  - deploy

test_v5:
  stage: test
  script:
    # Using `call` because this job runs on Windows
    # Installing dependencies, strictly based on lock file
    - call yarn --ignore-scripts --frozen-lockfile

    # Build only changed packages and its dependencies
    - call yarn lerna run build --include-dependencies --since

    # Test only changed packages and its dependents
    - call yarn lerna run test --concurrency=1 --include-dependents --since
  except:
    - v5@elf/refinitiv-ui
    - tags@elf/refinitiv-ui

release_v5:
  stage: deploy
  tags:
    - node
    - linux
  script:
    - git remote set-url origin https://git.sami.int.thomsonreuters.com/elf/refinitiv-ui.git
    - git checkout v5
    - git pull origin v5

    # Installing dependencies, strictly based on lock file
    - yarn --ignore-scripts --frozen-lockfile

    # Build only changed packages and its dependencies
    - yarn lerna run build --include-dependencies --since

    # Get changed packages version from conventional commit message
    - yarn lerna version --conventional-commits --conventional-prerelease --no-git-tag-version --yes

    # Publish to registry
    - yarn lerna publish from-package --yes --dist-tag next
  only:
    - v5@elf/refinitiv-ui
