before_script:
  # Setup credentials for pipeline
  - git clone -b v4 --single-branch git@git.sami.int.thomsonreuters.com:elf/gitlab-ci-tasks.git ci-tasks
  - node ci-tasks/before_script

stages:
  - test
  - deploy

release_v5_pre:
  stage: deploy
  tags:
    - node
    - linux
  script:
    - node --version
    - npm --version
    - git remote set-url origin https://git.sami.int.thomsonreuters.com/elf/refinitiv-ui.git
    - git checkout v5-version-path
    - git pull origin v5-version-path

    # Installing dependencies, strictly based on lock file
    - npm ci --ignore-scripts --audit=false --fund=false

    # Build only changed packages and its dependencies
    - npx lerna run build --include-dependencies --since

    # Get changed packages version from conventional commit message
    - npx lerna version --conventional-prerelease --conventional-commits --preid=next --yes

    # Publish to registry
    - npx lerna publish from-git --yes
  only:
    - v5-version-path@elf/refinitiv-ui
