before_script:
  # Setup credentials for pipeline
  - git clone -b v4 --single-branch git@git.sami.int.thomsonreuters.com:elf/gitlab-ci-tasks.git ci-tasks
  - node ci-tasks/before_script

stages:
  - test
  - deploy

test_v5:
  stage: test
  script:
    # Installing dependencies, strictly based on lock file
    - npm ci --ignore-scripts --audit=false --fund=false

    # Build only changed packages and its dependencies
    - npx lerna run build --include-dependencies --since

    # Test only changed packages and its dependents
    - npx lerna run test --concurrency=1 --include-dependents --since
  except:
    - v5@elf/refinitiv-ui
    - v5-dev@elf/refinitiv-ui
    - tags@elf/refinitiv-ui

release_v5:
  stage: deploy
  tags:
    - node
    - linux
  script:
    - git remote set-url origin https://git.sami.int.thomsonreuters.com/elf/refinitiv-ui.git
    - git checkout v5
    - git pull origin v5

    # Installing dependencies, strictly based on lock file
    - npm ci --ignore-scripts --audit=false --fund=false

    # Build only changed packages and its dependencies
    - npx lerna run build --include-dependencies --since

    # Get changed packages version from conventional commit message
    - npx lerna version --conventional-commits --conventional-prerelease --preid=beta --yes

    # Publish to registry
    - npx lerna publish from-git --yes --dist-tag next
  only:
    - v5@elf/refinitiv-ui
