name: 'Run BrowserStack Test'
description: 'Setup BrowserStack'
inputs:
  username:
    description: 'BrowserStack username'
    required: true
  access-key:
    description: 'BrowserStack access key'
    required: true
  mode:
    description: 'Test mode'
    required: false
    default: 'affected' # affected|all
  browsers:
    description: 'List of browser name'
    required: true
  coverage:
    description: 'Include test covertage'
    required: false
    default: 'true'
  base:
    description: 'Base sha for test affected mode'
    required: false
runs:
  using: "composite"
  steps:
    - name: 'BrowserStack Env Setup' # Invokes the setup-env action
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{ inputs.username }}
        access-key: ${{ inputs.access-key }}

    - name: 'BrowserStack Local Tunnel Setup' # Invokes the setup-local action
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-identifier: random

    - name: Setup resources and environment
      uses: ./.github/actions/setup
      id: setup

    - name: Test All
      if: ${{ inputs.mode == 'all' }}
      shell: bash
      # Prevent NX caching because it must run all testing, even though the code has not chaged.
      run: npm run test:all -- --parallel=3 --skip-nx-cache --browserstack '${{ inputs.browsers }}' --includeCoverage ${{ inputs.coverage }} --output minimal

    - name: Test Affected
      if: ${{ inputs.mode == 'affected' }}
      shell: bash
      # Parallel need to be 1 because Safari not stable when run parallel more than 1
      run: npm run test:affected -- --base=${{ inputs.base }} --parallel=1 --browserstack '${{ inputs.browsers }}' --includeCoverage ${{ inputs.coverage }} --output minimal

    - name: BrowserStackLocal Stop  # Terminating the BrowserStackLocal tunnel connection
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: stop



