name: Nightly Test
# on:
#   schedule:
#     - cron: '0 0 * * *'
on: [push] # Triggers on any branch
env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  BROWSERSTACK_BUILD: "Nightly Test ${{ github.run_number }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup
        id: setup

      - name: Install Dependencies
        if: steps.setup.outputs.cache-dependencies-hit != 'true'
        run: npm ci --ignore-scripts --audit=false --fund=false

      - name: Reset NX # temporary
        run: npm run reset

      - name: Build
        # Prevent NX caching it should always build
        run: npm run build -- --skip-nx-cache

  # lint:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Setup resources and environment
  #       uses: ./.github/actions/setup

  #     - name: Lint
  #       # Prevent NX caching because it must run all linting, even though the code has not chaged.
  #       run: npm run lint:all -- --skip-nx-cache

  # chrome:
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Test
  #       uses: ./.github/actions/browserstack
  #       with:
  #         browsers: 'chrome chrome_previous'
  #         mode: 'all'
  #         parallel: 1
  #         username: $BROWSERSTACK_USERNAME
  #         access-key: $BROWSERSTACK_ACCESS_KEY

  # firefox:
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Test
  #       uses: ./.github/actions/browserstack
  #       with:
  #         browsers: 'firefox firefox_previous'
  #         mode: 'all'
  #         coverage: 'false'
  #         parallel: 1
  #         username: $BROWSERSTACK_USERNAME
  #         access-key: $BROWSERSTACK_ACCESS_KEY

  safari:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        uses: ./.github/actions/browserstack
        with:
          browsers: 'safari safari_previous'
          mode: 'all'
          coverage: 'false'
          parallel: 1
          username: $BROWSERSTACK_USERNAME
          access-key: $BROWSERSTACK_ACCESS_KEY

      # Safari need to seprate test for each version to avoid unstable connection
      # - name: Test previous version
      #   uses: ./.github/actions/browserstack
      #   with:
      #     browsers: 'safari_previous'
      #     mode: 'all'
      #     coverage: 'false'
      #     parallel: 1
      #     username: $BROWSERSTACK_USERNAME
      #     access-key: $BROWSERSTACK_ACCESS_KEY
      #     setup: 'false'

  # edge:
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Test
  #       uses: ./.github/actions/browserstack
  #       with:
  #         browsers: 'edge edge_previous'
  #         mode: 'all'
  #         parallel: 1
  #         username: $BROWSERSTACK_USERNAME
  #         access-key: $BROWSERSTACK_ACCESS_KEY
