name: Test
on:
  pull_request:
    branches: [develop]
env:
  BEFORE_SHA: ${{ github.event.before }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup
        id: setup

      - name: Install Dependencies
        if: steps.setup.outputs.cache-dependencies-hit != 'true'
        run: npm ci --ignore-scripts --audit=false --fund=false

      - name: Build
        if: steps.setup.outputs.cache-build-hit != 'true'
        run: npm run build:affected -- --base=$BEFORE_SHA

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup

      - name: Lint
        run: npm run lint:affected -- --base=$BEFORE_SHA

  chrome:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup

      - name: Test
        run: npm run test:affected -- --base=$BEFORE_SHA --browsers chrome

  firefox:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup

      - name: Test
        # TODO: `@refinitiv/core` has test coverage below threshold on Firefox
        run: npm run test:affected -- --base=$BEFORE_SHA --browsers firefox --includeCoverage false
